name: Go

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'docs:') }}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ^1.22
      id: go
    - uses: actions/checkout@v4
    - run: make style
    - run: make vet
    - run: make test
    - run: make build
