name: Build and Publish artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: Build and upload artifacts

    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Promu - Crossbuild
        run: make crossbuild

      - name: Promu - Prepare packages
        run: make crossbuild-tarballs

      - name: Calculate checksums
        run: make crossbuild-checksum

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .tarballs/*

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
